---
title: "Problemas Inversos em Python"
author: "Sergio Pedro Rodrigues Oliveira"
date: last-modified
date-format: DD MMMM YYYY
format:
    html:
        code-fold: true
        number-sections: true
    pdf:
      toc: false
      lof: false
      lot: false
      toc-depth: 5
      number-sections: true
      number-depth: 5
      colorlinks: true
      cite-method: biblatex
    docx:
      toc: true
      number-sections: true
      highlight-style: github
jupyter: python3
bibliography: Quarto/bibliografia.bib
csl: Quarto/abnt.csl
---

\thispagestyle{empty}

\newpage
\pagenumbering{roman}
```{=latex}
\setcounter{tocdepth}{4}
\renewcommand{\contentsname}{SUMÁRIO}
\tableofcontents
```

\newpage

```{=latex}
\setcounter{tocdepth}{4}
\renewcommand{\listfigurename}{LISTA DE FIGURAS}
\listoffigures
```

\newpage

```{=latex}
\setcounter{tocdepth}{4}
\renewcommand{\listtablename}{LISTA DE TABELAS}
\listoftables
```

```{python}
#| echo: false
#| error: false
#| warning: false
from IPython.display import Markdown
from tabulate import tabulate
import math
import statistics
import numpy as np
import pandas as pd
import datetime 
```

\newpage
\pagenumbering{arabic}

# PRINCIPAIS TÓPICOS

## Tópicos

- Principais tópicos de revisão de Python (@paiva2021introduccao)
  - `printf`
  - Operações básicas
  - Condicionais - `if`, `else` e `elif`
  - Loops - `for` e `while`
  - Função - `def`
  - Listas - `list`
- Bibliotecas
  - numpy

## Tarefas

- 30/10/24
  - Qual biblioteca Python é melhor para trabalhar com matrizes?  
  `numpy`
  
  - Como importar bibliotecas?  
  `import nome_biblioteca`  
  Exemplo:  
  `import numpy as np`

- Seminário 1
  - Trabalho computacional 1
    - Lista de exercícios
    - Relatório técnico (qmd -> pdf)
    - Exemplo compilado (comentar código)
    - Trazer programas e trabalho em pendrive
    - Data de entrega: 27/11/24

\newpage

# REVISÃO DE PYTHON

\newpage

# BIBLIOTECAS
  
## Importando biblioteca

Para importar uma biblioteca instalada no sistema para o arquivo Python (`.py`):

1. `import nome_biblioteca as apelido_biblioteca`
   
2. `from nome_biblioteca import nome_função`

## `numpy`

\newpage

# ESTATÍSTICA BÁSICA

\newpage

# INTRODUÇÃO A PROBLEMAS INVERSOS

\newpage

# BIBLIOGRAFIA